# Generated by Django 5.0.7 on 2024-07-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
